import assert from 'node:assert/strict';
import {prepareBlockMove,listBlockContainers,prepareBlockInsert,prepareBlockDuplicate,prepareBlockRemove,createContentBlock} from '../dist/layout.js';
import {createEditorSession,getValueAtPath} from '../dist/index.js';
const deck={name:'Keep deck metadata',extensions:{blocks:[{text:'Not a content group'}]},slides:[{id:'s',notes:'Keep notes',composition:{mode:'row',weights:[3,1,2]},blocks:[{text:[{text:'A',bold:true,link:'https://example.org'}]},{composition:{mode:'column',weights:[2,1]},blocks:[{text:'B'},{table:{columns:['Q','R'],rows:[['Q1',12]]}}]},{text:'C'}]},{title:'Next',blocks:[{text:'D'},{text:'E'}]}]};
const original=structuredClone(deck);
assert.deepEqual(listBlockContainers(deck).map(c=>c.path),['/slides/0','/slides/0/blocks/1','/slides/1']);
const later=prepareBlockMove(deck,'slides.0.blocks.0','slides.0',3);
assert.deepEqual(later.document.slides[0].blocks,[deck.slides[0].blocks[1],deck.slides[0].blocks[2],deck.slides[0].blocks[0]]);
assert.equal(later.path,'/slides/0/blocks/2');assert.deepEqual(later.document.slides[0].composition,deck.slides[0].composition);assert.deepEqual(deck,original);
const earlier=prepareBlockMove(deck,'/slides/0/blocks/2','/slides/0',0);assert.equal(earlier.document.slides[0].blocks[0].text,'C');
const intoShiftedGroup=prepareBlockMove(deck,'slides.0.blocks.0','slides.0.blocks.1',1);
assert.equal(intoShiftedGroup.path,'/slides/0/blocks/0/blocks/1');assert.deepEqual(getValueAtPath(intoShiftedGroup.document,intoShiftedGroup.path),deck.slides[0].blocks[0]);
assert.deepEqual(intoShiftedGroup.document.slides[0].blocks[0].composition,deck.slides[0].blocks[1].composition);
const out=prepareBlockMove(deck,'slides.0.blocks.1.blocks.0','slides.0',0);assert.equal(out.document.slides[0].blocks[0].text,'B');assert.deepEqual(out.document.slides[0].blocks[2].blocks,[deck.slides[0].blocks[1].blocks[1]]);
const across=prepareBlockMove(deck,'slides.0.blocks.1','slides.1',1);assert.deepEqual(across.document.slides[1].blocks[1],deck.slides[0].blocks[1]);assert.equal(across.document.slides[0].notes,'Keep notes');
assert.throws(()=>prepareBlockMove(deck,'slides.0.blocks.1','slides.0.blocks.1',0),/itself/);
const single={slides:[{blocks:[{blocks:[{text:'Only child'}]},{text:'Other'}]}]};assert.throws(()=>prepareBlockMove(single,'slides.0.blocks.0.blocks.0','slides.0',1),/empty/);
assert.throws(()=>prepareBlockMove(deck,'slides.0.blocks.0','extensions',0),/slide or group/);
for(const i of [-1,1.5,99])assert.throws(()=>prepareBlockMove(deck,'slides.0.blocks.0','slides.0',i));
assert.throws(()=>prepareBlockMove(deck,'slides.0.blocks.0.text','slides.0',1),/complete block/);
for(const i of [0,1]){const noop=prepareBlockMove(deck,'slides.0.blocks.0','slides.0',i);assert.equal(noop.changed,false);assert.deepEqual(noop.patches,[]);assert.deepEqual(noop.document,deck);}
const editor=createEditorSession(deck,{rejectInvalid:true});editor.applyPatch(later.patches);editor.undo();assert.deepEqual(editor.document,deck);assert.equal(editor.canUndo,false);
editor.set('name','Newer independent name');editor.applyPatch(later.patches);assert.equal(editor.get('name'),'Newer independent name');editor.undo();assert.deepEqual(editor.get('slides'),deck.slides);
editor.set('slides.0.notes','Newer notes');assert.throws(()=>editor.applyPatch(later.patches));assert.equal(editor.get('slides.0.notes'),'Newer notes');
const promoted={slides:[{left:{blocks:[{text:'L1'},{text:'L2'}]},right:{blocks:[{text:'R'}]}}]};const moved=prepareBlockMove(promoted,'slides.0.left.blocks.0','slides.0.right',1);assert.equal(moved.document.slides[0].right.blocks[1].text,'L1');
console.log('Block moves passed: sibling order, shifted group destinations, nested/ancestor/cross-slide moves, formatting/data preservation, no-op, cycle/empty rejection, guards and undo.');

const implicit={name:'Keep metadata',assets:{},slides:[{id:'one',title:'Keep title',subtitle:'Keep subtitle',notes:'Keep notes',design:{fontScheme:'roboto'},composition:{mode:'row',weights:[3,1]},text:[{text:'Preserve rich text',bold:true}],items:['Preserve items']}]};
const inserted=prepareBlockInsert(implicit,'slides.0',createContentBlock('metric'),1);
assert.equal(inserted.path,'/slides/0/blocks/1');
assert.deepEqual(inserted.document.slides[0].blocks,[{text:implicit.slides[0].text},createContentBlock('metric'),{items:implicit.slides[0].items}]);
const {blocks:ignored,...metadata}=inserted.document.slides[0];const {text:ignored2,items:ignored3,...expectedMetadata}=implicit.slides[0];assert.deepEqual(metadata,expectedMetadata);
assert.deepEqual(prepareBlockInsert({slides:[{type:'text',bullets:['Keep bullet']}]},'slides.0',{text:'New'}).document.slides[0].blocks[0],{type:'text',bullets:['Keep bullet']});
const insertedRegion=prepareBlockInsert({slides:[{left:{text:'Left'},right:{text:'Right'}}]},'slides.0.left',{items:['New']});assert.deepEqual(insertedRegion.document.slides[0].left.blocks,[{text:'Left'},{items:['New']}]);
assert.throws(()=>prepareBlockInsert({slides:[{left:{text:'Left'}}]},'slides.0',{text:'Mixed'}),/container/);
assert.deepEqual(listBlockContainers(implicit,{includeImplicit:true}).map(c=>c.path),['/slides/0']);
assert.deepEqual(listBlockContainers(implicit),[]);
const duplicate=prepareBlockDuplicate(deck,'slides.0.blocks.1');assert.deepEqual(duplicate.document.slides[0].blocks[2],deck.slides[0].blocks[1]);assert.notEqual(duplicate.document.slides[0].blocks[2],duplicate.document.slides[0].blocks[1]);
const removed=prepareBlockRemove(single,'slides.0.blocks.0.blocks.0');assert.deepEqual(removed.document.slides[0].blocks,[{text:'Other'}]);
const empty=prepareBlockRemove({slides:[{title:'Retained slide',blocks:[{blocks:[{blocks:[{text:'Only'}]}]}]}]},'slides.0.blocks.0.blocks.0.blocks.0');assert.deepEqual(empty.document.slides,[{title:'Retained slide',blocks:[]}]);
const regionRemoved=prepareBlockRemove({slides:[{notes:'Retain notes',left:{blocks:[{blocks:[{text:'Only'}]}]},right:{text:'Context'}}]},'slides.0.left.blocks.0.blocks.0');assert.deepEqual(regionRemoved.document.slides[0],{notes:'Retain notes',right:{text:'Context'}});
for(const kind of ['text','list','chart','table','metric','quote','code','timeline','group','image','video'])prepareBlockInsert({slides:[{title:'Blank'}]},'slides.0',createContentBlock(kind,{source:'https://example.org/media'}));
assert.throws(()=>createContentBlock('image'),/source/);assert.throws(()=>createContentBlock('unknown'),/Unknown/);
for(const index of [-1,1.5,99])assert.throws(()=>prepareBlockInsert(implicit,'slides.0',{text:'x'},index));
assert.throws(()=>prepareBlockInsert(implicit,'extensions',{text:'x'}));
assert.throws(()=>prepareBlockInsert(implicit,'slides.0',{unknown:'Invalid'}));
assert.throws(()=>prepareBlockRemove(deck,'slides.0.blocks.0.text'));
const history=createEditorSession(implicit,{rejectInvalid:true});history.applyPatch(inserted.patches);history.undo();assert.deepEqual(history.document,implicit);
history.set('name','Independent change');history.applyPatch(inserted.patches);assert.equal(history.get('name'),'Independent change');history.undo();history.set('slides.0.notes','Concurrent edit');assert.throws(()=>history.applyPatch(inserted.patches));
const removalHistory=createEditorSession(single,{rejectInvalid:true});removalHistory.applyPatch(removed.patches);removalHistory.undo();assert.deepEqual(removalHistory.document,single);
console.log('Block creation passed: presets, implicit normalization, groups/regions, duplication, empty ancestor pruning, guards, metadata and undo.');
