import assert from 'node:assert/strict';
import {EditorState,Transaction} from '@codemirror/state';
import {history,undo,redo,isolateHistory} from '@codemirror/commands';
import {jsonSource,jsonSourceHistory,setJsonSource} from '../src/json-source.js';

const original='First\r\nSecond\rThird\n';
let state;
const reset=()=>state=EditorState.create({doc:original,extensions:[history(),jsonSource.init(()=>original),jsonSourceHistory]});
const apply=spec=>state=state.update({...spec,annotations:[...(spec.annotations??[]),isolateHistory.of('full')]}).state;
const target=()=>({state,dispatch:tr=>state=tr.state});
const source=()=>state.field(jsonSource);
reset();assert.equal(state.doc.toString(),'First\nSecond\nThird\n');assert.equal(source(),original);
apply({changes:{from:5,insert:'!'}});assert.equal(source(),'First!\r\nSecond\rThird\n');
assert.ok(undo(target()));assert.equal(source(),original);assert.ok(redo(target()));assert.equal(source(),'First!\r\nSecond\rThird\n');
reset();apply({changes:{from:12,to:13}});assert.equal(source(),'First\r\nSecondThird\n');
assert.ok(undo(target()));assert.equal(source(),original);assert.ok(redo(target()));assert.equal(source(),'First\r\nSecondThird\n');
reset();apply({changes:[{from:5,to:6},{from:12,to:13}]});assert.equal(source(),'FirstSecondThird\n');assert.ok(undo(target()));assert.equal(source(),original);
reset();apply({changes:{from:0,to:state.doc.length}});apply({changes:{from:0,insert:'New\n'}});assert.equal(source(),'New\n');
assert.ok(undo(target()));assert.equal(source(),'');assert.ok(undo(target()));assert.equal(source(),original);
assert.ok(redo(target()));assert.ok(redo(target()));assert.equal(source(),'New\n');
reset();const pasted='Pasted\rwith\r\nends\n';apply({changes:{from:0,to:state.doc.length,insert:pasted},effects:setJsonSource.of(pasted)});
assert.equal(source(),pasted);assert.ok(undo(target()));assert.equal(source(),original);assert.ok(redo(target()));assert.equal(source(),pasted);
reset();apply({changes:{from:12,to:13}});const external='External\n'+source();
apply({changes:{from:0,insert:'External\n'},effects:setJsonSource.of(external),annotations:[Transaction.addToHistory.of(false)]});
assert.ok(undo(target()));assert.equal(source(),'External\n'+original,'Undo must preserve unrelated external source and restore the removed CR');
assert.ok(redo(target()));assert.equal(source(),external);
reset();
for(let i=0;i<2;i++)state=state.update({changes:{from:5,to:6,insert:'\n'},effects:setJsonSource.of(source().replace('\r\n','\n')),annotations:Transaction.userEvent.of('input.type')}).state;
assert.ok(undo(target()));assert.equal(source(),original,'Grouped edits of one separator must restore its first spelling');
assert.ok(redo(target()));assert.equal(source(),original.replace('\r\n','\n'));
reset();assert.throws(()=>apply({effects:setJsonSource.of('Different content')}),/must agree/);assert.equal(source(),original);
console.log('JSON source: exact mixed endings through typing, multi-range edits, deletion, native history, explicit paste and external changes.');
