import assert from 'node:assert/strict';
import {composeSlide} from '@openpresentation/opf/composition';
import {prepareTrackResize} from '../dist/layout.js';
import {createEditorSession} from '../dist/index.js';
const deck={name:'Preserved',slides:[{id:'flow',title:'Shared tracks',composition:{mode:'row',weights:[2,1,1],gap:.02},blocks:[{text:'One'},{composition:{mode:'column'},blocks:[{text:'Two'},{text:'Three'}]},{text:'Four'}]}]};
const geometry=composeSlide(deck.slides[0]);
assert.equal(geometry.flows.length,2);
const flow=geometry.flows[0],nested=geometry.flows[1];
assert.equal(flow.path,'slides.0');assert.equal(nested.path,'slides.0.blocks.1');
assert.equal(flow.columns.length,3);assert.equal(nested.rows.length,2);
assert.equal(flow.itemCount,3);assert.equal(flow.slotCount,3);
const first=geometry.items.find(i=>i.path==='slides.0.blocks.0.text');
assert.ok(Math.abs(first.box.width-flow.columns[0].size)<1e-6);
const prepared=prepareTrackResize(deck,flow,0,.5);
assert.deepEqual(prepared.composition.weights,[1.5,1.5,1]);
assert.equal(prepared.document.name,deck.name);assert.deepEqual(prepared.document.slides[0].blocks,deck.slides[0].blocks);
assert.deepEqual(deck.slides[0].composition.weights,[2,1,1]);
const resized=composeSlide(prepared.document.slides[0]);
assert.equal(resized.flows[0].columns[2].size,flow.columns[2].size);
assert.ok(Math.abs(resized.flows[0].columns[0].size-resized.flows[0].columns[1].size)<1e-8);
const child=prepareTrackResize(deck,nested,0,.75);
assert.deepEqual(child.document.slides[0].composition,deck.slides[0].composition);
assert.deepEqual(child.composition.weights,[1.5,.5]);
const auto={slides:[{blocks:[{text:'A'},{text:'B'},{text:'C'},{text:'D'}]}]};
const autoFlow=composeSlide(auto.slides[0]).flows[0];assert.ok(autoFlow.columns.length>1);
const frozen=prepareTrackResize(auto,autoFlow,0,.6);assert.equal(frozen.composition.mode,'grid');assert.equal(frozen.composition.columns,autoFlow.columns.length);
const maxDeck={slides:[{composition:{mode:'row',weights:[100,100,100]},blocks:[{text:'A'},{text:'B'},{text:'C'}]}]};
const maxFlow=composeSlide(maxDeck.slides[0]).flows[0],max=prepareTrackResize(maxDeck,maxFlow,0,.95);
assert.ok(max.composition.weights.every(w=>w>0&&w<=100));
const after=composeSlide(max.document.slides[0]).flows[0];assert.ok(Math.abs(after.columns[2].size-maxFlow.columns[2].size)<1e-7);
assert.equal(prepareTrackResize(deck,flow,0,0).fraction,.05);
for(const [boundary,fraction]of [[-1,.5],[2,.5],[0,NaN],[0,2]])assert.throws(()=>prepareTrackResize(deck,flow,boundary,fraction));
const reserved=composeSlide(deck.slides[0],{layout:{placeholders:Array.from({length:6},()=>({type:'text'}))}}).flows[0];assert.equal(reserved.slotCount,3); // explicit row ignores slots
const legacy={slides:[{blocks:[{text:'A'},{text:'B'}]}]};const legacyFlow=composeSlide(legacy.slides[0],{layout:{placeholders:Array.from({length:6},()=>({type:'text'}))}}).flows[0];
assert.throws(()=>prepareTrackResize(legacy,legacyFlow,0,.6),/explicit arrangement/);
const promoted=composeSlide({left:{text:'Fixed'},right:{blocks:[{text:'Top'},{text:'Bottom'}],composition:{mode:'column'}}});
assert.deepEqual(promoted.flows.map(f=>f.path),['slides.0.right']);
const editor=createEditorSession(deck,{rejectInvalid:true});editor.applyPatch(prepared.patches);editor.undo();assert.deepEqual(editor.document,deck);assert.equal(editor.canUndo,false);
editor.set('slides.0.title','Newer title');assert.throws(()=>editor.applyPatch(prepared.patches));assert.equal(editor.get('slides.0.title'),'Newer title');
console.log('Layout resizing passed: exact track geometry, row/column/nested/grid behavior, auto freeze, weight bounds, metadata preservation, stale guards and undo.');

const guard=createEditorSession({slides:[{title:'Before'}],extensions:{a:1,b:[false,null]}});
guard.applyPatch([{op:'test',path:'/extensions',value:{b:[false,null],a:1}}]);assert.equal(guard.canUndo,false);
assert.throws(()=>guard.applyPatch([{op:'replace',path:'/slides/0/title',value:'Transient'},{op:'test',path:'/slides/0/title',value:'Wrong'}]));
assert.equal(guard.get('slides.0.title'),'Before');assert.equal(guard.canUndo,false);
assert.throws(()=>guard.applyPatch([{op:'test',path:'/missing',value:null}]));
assert.throws(()=>guard.applyPatch([{op:'test',path:'/slides/0/title'}]));

const cardDocument={design:{contentBox:true},slides:[{blocks:[{text:'Exact source. '.repeat(80)}]}]};
const cardEditor=createEditorSession(cardDocument,{rejectInvalid:true});
assert.ok(cardEditor.composeSlide(0).items.every(item=>item.frameBox));
cardEditor.paginateSlide(0,{minFontSize:25});
assert.ok(cardEditor.composeSlide(0).items.every(item=>item.frameBox));
cardEditor.undo();assert.deepEqual(cardEditor.document,cardDocument);
cardEditor.set('slides.0.design',{contentBox:false});assert.ok(cardEditor.composeSlide(0).items.every(item=>!item.frameBox));
cardEditor.undo();assert.deepEqual(cardEditor.document,cardDocument);
