import assert from 'node:assert/strict';
import {formatRichTextRange as format, replaceRichTextRange as replace, richTextContent as content} from '../dist/rich-text.js';
import {createEditorSession} from '../dist/index.js';
const original=['Hello ',{text:'bold world',bold:true,link:'https://example.org',extension:{keep:true}},'!'];
const copy=structuredClone(original);
const changed=format(original,3,9,{italic:true});
assert.equal(content(changed),'Hello bold world!');
assert.deepEqual(changed,['Hel',{text:'lo ',italic:true},{text:'bol',bold:true,italic:true,link:'https://example.org',extension:{keep:true}},{text:'d world',bold:true,link:'https://example.org',extension:{keep:true}},'!']);
assert.deepEqual(original,copy);
changed[2].extension.keep=false;assert.equal(original[1].extension.keep,true);
assert.deepEqual(format([{text:'Hi',bold:true,italic:true}],0,2,{bold:false,italic:null}),[{text:'Hi',bold:false}]);
assert.deepEqual(format([{text:'2',subscript:true}],0,1,{superscript:true}),[{text:'2',subscript:false,superscript:true}]);
assert.equal(content(replace(original,3,9,'new')),'Helnewd world!');
assert.equal(content(replace(original,0,content(original).length,'')),'');
assert.deepEqual(replace([{text:'abcd',bold:true}],1,3,'XX'),[{text:'a',bold:true},{text:'XX',bold:true},{text:'d',bold:true}]);
assert.equal(content(replace(['ab','cd'],2,2,'!')),'ab!cd');
assert.equal(content(replace([],0,0,'First')),'First');
assert.equal(content(replace('abc',3,3,'!')),'abc!');
for(const [start,end] of [[-1,2],[0,99],[2,1],[1.5,2],[0,0]])assert.throws(()=>format(original,start,end,{bold:true}));
for(const text of ['a😀b','ae\u0301b','a👩‍👩‍👧‍👧b'])assert.throws(()=>format(text,1,2,{bold:true}),/grapheme/);
assert.equal(content(format('ae\u0301b',1,3,{bold:true})),'ae\u0301b');
for(const patch of [{text:'oops'},{fontSize:0},{fontSize:NaN},{bold:'yes'},{superscript:true,subscript:true},JSON.parse('{"__proto__":{}}')])assert.throws(()=>format('text',0,4,patch));
const editor=createEditorSession({slides:[{text:original,notes:'Preserve'}]},{rejectInvalid:true});
editor.set('slides.0.text',format(original,0,5,{color:'#2563eb'}),{rejectInvalid:true});
assert.equal(editor.get('slides.0.notes'),'Preserve');editor.undo();assert.deepEqual(editor.get('slides.0.text'),original);assert.equal(editor.canUndo,false);
console.log('Rich range editing passed: cross-run preservation, replacement, style removal, script exclusivity, grapheme safety, validation and atomic undo.');

const {updateRichTextInput} = await import('../dist/rich-text.js');
const typed=[{text:'Hello ',bold:true,link:'https://example.org'}, {text:'world',italic:true,fontSize:24}];
assert.deepEqual(updateRichTextInput(typed,'Hello brave world',{start:6,end:6,inputType:'insertText'}),[{text:'Hello brave ',bold:true,link:'https://example.org'},{text:'world',italic:true,fontSize:24}]);
assert.deepEqual(updateRichTextInput([{text:'a',bold:true},{text:'a',italic:true}],'aaa',{start:0,end:0,inputType:'insertText'}),[{text:'aa',bold:true},{text:'a',italic:true}]);
assert.deepEqual(updateRichTextInput([{text:'a',bold:true},{text:'a',italic:true}],'a',{start:0,end:1,inputType:'deleteContentBackward'}),[{text:'a',italic:true}]);
assert.equal(content(updateRichTextInput([{text:'A👩‍💻B',bold:true}],'A👩‍🔬B')),'A👩‍🔬B');
assert.deepEqual(updateRichTextInput([{text:'cafe',italic:true}], 'café'),[{text:'café',italic:true}]);
let repeated=[{text:'A',bold:true}];for(let i=0;i<100;i++)repeated=updateRichTextInput(repeated,content(repeated)+'a');
assert.equal(repeated.length,1,'continuous typing compacts equal adjacent styles');
assert.equal(typed[0].text,'Hello ','native typing must not mutate the source');
console.log('Native rich input passed: style/link preservation, repeated-character affinity, graphemes and bounded run growth.');

const mixedEndings=[{text:'First\r\n',bold:true,link:'https://example.org'},{text:'Second\rThird',italic:true,extension:{keep:'second'}}];
const mixedCopy=structuredClone(mixedEndings);
assert.deepEqual(updateRichTextInput(mixedEndings,'First\nSecond\nThird!',{start:18,end:18,inputType:'insertText'}),[mixedEndings[0],{...mixedEndings[1],text:'Second\rThird!'}],'appending after mixed line endings preserves source and later styles');
assert.deepEqual(updateRichTextInput(mixedEndings,'First\nSecond\nThird'),mixedEndings,'native newline normalization alone is not a source edit');
let edited=updateRichTextInput(mixedEndings,'First!\nSecond\nThird',{start:5,end:5,inputType:'insertText'});
edited=updateRichTextInput(edited,'First!\nSecond\nThird?',{start:19,end:19,inputType:'insertText'});
assert.deepEqual(edited,[{...mixedEndings[0],text:'First!\r\n'},{...mixedEndings[1],text:'Second\rThird?'}],'separate edits do not rewrite untouched line endings between them');
assert.deepEqual(updateRichTextInput(mixedEndings,'FirstSecond\nThird',{start:5,end:6,inputType:'deleteContentForward'}),[{...mixedEndings[0],text:'First'},mixedEndings[1]],'deleting one native newline removes the complete source CRLF');
assert.deepEqual(updateRichTextInput(mixedEndings,'First\nSecond\nNew\nThird',{start:13,end:13,inputType:'insertLineBreak'}),[mixedEndings[0],{...mixedEndings[1],text:'Second\rNew\r\nThird'}],'new line endings follow the established scalar input convention');
const splitEnding=[{text:'A\r',bold:true},{text:'\nB',italic:true}];
assert.deepEqual(updateRichTextInput(splitEnding,'A\nB!',{start:3,end:3,inputType:'insertText'}),[splitEnding[0],{...splitEnding[1],text:'\nB!'}],'a CRLF split across styled runs stays intact');
const repeatedAfterLine=[{text:'X\r\na',bold:true},{text:'a',italic:true}];
assert.deepEqual(updateRichTextInput(repeatedAfterLine,'X\naaa',{start:2,end:2,inputType:'insertText'}),[{text:'X\r\naa',bold:true},repeatedAfterLine[1]],'native affinity after a CRLF stays with the selected run');
const markedAfterLine=[{text:'A\r\n',bold:true},{text:'e\u0301😀',italic:true}];
assert.deepEqual(updateRichTextInput(markedAfterLine,'A\né😀',{start:2,end:4,inputType:'insertCompositionText'}),[markedAfterLine[0],{text:'é😀',italic:true}],'source mapping preserves whole graphemes after a CRLF');
assert.deepEqual(mixedEndings,mixedCopy);
console.log('Native rich input preserves mixed source line endings, cross-run CRLF, selection affinity, marks and metadata.');
